---
repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 43.19.2
    hooks:
      - id: renovate-config-validator
        files: renovate-config.js
