---
repos:
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.8
    hooks:
      - id: actionlint

  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 42.1.3
    hooks:
      - id: renovate-config-validator
        files: renovate-config.js
